spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clevertec
    username: postgres
    password: 172143
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    web: debug
