spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show_sql: false
    properties:
      hibernate:
        format_sql: false
  liquibase:
    enabled: false